export const COUNTRIES = [
  { name: "فلسطين", iso: "ps", code: "+970" },
  { name: "إسرائيل", iso: "il", code: "+972" },
  { name: "مصر", iso: "eg", code: "+20" },
  { name: "السعودية", iso: "sa", code: "+966" },
  { name: "الإمارات", iso: "ae", code: "+971" },
  { name: "الأردن", iso: "jo", code: "+962" },
  { name: "لبنان", iso: "lb", code: "+961" },
  { name: "سوريا", iso: "sy", code: "+963" },
  { name: "العراق", iso: "iq", code: "+964" },
  { name: "الكويت", iso: "kw", code: "+965" },
  { name: "قطر", iso: "qa", code: "+974" },
  { name: "البحرين", iso: "bh", code: "+973" },
  { name: "عُمان", iso: "om", code: "+968" },
  { name: "اليمن", iso: "ye", code: "+967" },
  { name: "ليبيا", iso: "ly", code: "+218" },
  { name: "الجزائر", iso: "dz", code: "+213" },
  { name: "المغرب", iso: "ma", code: "+212" },
  { name: "تونس", iso: "tn", code: "+216" },
  { name: "السودان", iso: "sd", code: "+249" },
  { name: "تركيا", iso: "tr", code: "+90" },
  { name: "إيران", iso: "ir", code: "+98" },
  { name: "أفغانستان", iso: "af", code: "+93" },
  { name: "باكستان", iso: "pk", code: "+92" },
  { name: "الهند", iso: "in", code: "+91" },
  { name: "بنغلاديش", iso: "bd", code: "+880" },
  { name: "الصين", iso: "cn", code: "+86" },
  { name: "اليابان", iso: "jp", code: "+81" },
  { name: "كوريا الجنوبية", iso: "kr", code: "+82" },
  { name: "ماليزيا", iso: "my", code: "+60" },
  { name: "إندونيسيا", iso: "id", code: "+62" },
  { name: "الفلبين", iso: "ph", code: "+63" },
  { name: "تايلاند", iso: "th", code: "+66" },
  { name: "المالديف", iso: "mv", code: "+960" },
  { name: "قبرص", iso: "cy", code: "+357" },
  { name: "مالطا", iso: "mt", code: "+356" },
  { name: "أذربيجان", iso: "az", code: "+994" },
  { name: "أرمينيا", iso: "am", code: "+374" },
  { name: "جورجيا", iso: "ge", code: "+995" },
  { name: "أوزبكستان", iso: "uz", code: "+998" },
  { name: "كازاخستان", iso: "kz", code: "+7" },
  { name: "روسيا", iso: "ru", code: "+7" },
  { name: "أوكرانيا", iso: "ua", code: "+380" },
  { name: "بولندا", iso: "pl", code: "+48" },
  { name: "رومانيا", iso: "ro", code: "+40" },
  { name: "المجر", iso: "hu", code: "+36" },
  { name: "التشيك", iso: "cz", code: "+420" },
  { name: "اليونان", iso: "gr", code: "+30" },
  { name: "ألمانيا", iso: "de", code: "+49" },
  { name: "فرنسا", iso: "fr", code: "+33" },
  { name: "إيطاليا", iso: "it", code: "+39" },
  { name: "إسبانيا", iso: "es", code: "+34" },
  { name: "البرتغال", iso: "pt", code: "+351" },
  { name: "أيرلندا", iso: "ie", code: "+353" },
  { name: "المملكة المتحدة", iso: "gb", code: "+44" },
  { name: "هولندا", iso: "nl", code: "+31" },
  { name: "بلجيكا", iso: "be", code: "+32" },
  { name: "سويسرا", iso: "ch", code: "+41" },
  { name: "النمسا", iso: "at", code: "+43" },
  { name: "السويد", iso: "se", code: "+46" },
  { name: "النرويج", iso: "no", code: "+47" },
  { name: "الدنمارك", iso: "dk", code: "+45" },
  { name: "فنلندا", iso: "fi", code: "+358" },
  { name: "نيوزيلندا", iso: "nz", code: "+64" },
  { name: "أستراليا", iso: "au", code: "+61" },
  { name: "الولايات المتحدة", iso: "us", code: "+1" },
  { name: "كندا", iso: "ca", code: "+1" },
  { name: "المكسيك", iso: "mx", code: "+52" },
  { name: "البرازيل", iso: "br", code: "+55" },
  { name: "الأرجنتين", iso: "ar", code: "+54" },
  { name: "تشيلي", iso: "cl", code: "+56" },
  { name: "كولومبيا", iso: "co", code: "+57" },
  { name: "جنوب أفريقيا", iso: "za", code: "+27" },
  { name: "نيجيريا", iso: "ng", code: "+234" },
  { name: "إثيوبيا", iso: "et", code: "+251" },
  { name: "كينيا", iso: "ke", code: "+254" },
];

export const DEFAULT_COUNTRY = COUNTRIES[0];
